name: Deploy to Live Channel

on:
  push:
    branches:
      - "main"
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

env:
  BACKEND_URL: ${{secrets.BACKEND_URL}}
  GOOGLE_MAPS_API_KEY: ${{secrets.GOOGLE_MAPS_API_KEY}}

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - run: npm ci && npm run build
        env:
          CI: false

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVACUATION_FDC5B }}"
          projectId: evacuation-fdc5b
          channelId: live
        env:
          FIREBASE_TOKEN: "${{ secrets.FIREBASE_TOKEN }}"
